### ISSUE TITLE
Navigation is not closed when something is selected on small screens

### ISSUE THREAD

**Issue by srinivaskarri1999** [blotoutio/website#134]
If we click on Product, navigation is not collapsed on small screens.
we need to manually close it to see the content.

![image](https://user-images.githubusercontent.com/34010703/139817132-92e87502-aee8-4870-83ff-31c0ade10468.png)

**Comment by yashghelani** [comment]
Thanks for reporting @srinivaskarri1999 PR #135 will fix this

**Comment by yashghelani** [comment]
@srinivaskarri1999 There’s a staging link in the PR comments that you can test. The URL keeps changing with new commits

**Comment by srinivaskarri1999** [comment]
yes, this issue got fixed by PR #135 
thank you.
