### ISSUE TITLE
Fixes to get to Alpha

### ISSUE THREAD

**Issue by matthewboulos** [blotoutio/website#40]
# Structure/Layout

### Font
- [x] Change to Inter
- [x] Decide on monospace font

### Clean up navigation
- [x] Fix for mobile (clicking hamburger doesn't do anything)
- [x] Do not change weight/background of link when mouseover, just show the drop-down box
- [x] "Company" should not have a drop-down --> direct link to About page
- [x] "Product" should not have a drop-down (for now) --> link to Marketer section
- [x] Give drop-down box rounded corners (border-radius: 5px;)

### Accessibility, SEO, etc.
- [x] Use h1-h6 for titles to increase our SEO and semantics
- [x] Change buttons from divs to a or button html tags
- [x] Add meta data
- [x] Fix lighthouse:
![image](https://user-images.githubusercontent.com/15007821/128573683-ce7abddf-a5e8-4c25-b224-16a2b6ae7fde.png)
- [x] Fix console errors:
![image](https://user-images.githubusercontent.com/75333858/129120820-6e959a44-6498-447d-a1b4-8e8a65db5f14.png)
![image](https://user-images.githubusercontent.com/15007821/128573359-d216f049-70df-4fe9-bc49-67db47af4e0d.png)
- [x] Make the width of content (example text on the Privacy and Terms pages) from 650px to 800-900px

### Links

- [x] Make sure nav and footer links all work
- [x] Add Slack link to the button (grab from current home page)
- [x] Add Calendly link to CTA (get from Markus)

---

# Copy/Content

### Hero
- [x] Change sub-heading to: "Your third-party analytics and marketing tools are bleeding data. Blotout gives you the turnkey cloud prem infrastructure and solutions to solve this."
- [x] Brand logos: Razer and Uphold for sure, waiting on the others
- [x] Above the logos: "Trusted by privacy-first organizations"

### Explainer
- [x] Create the explainer section
I've put the illustration and layout for the explainer section in Frame 441 in [Figma](https://www.figma.com/file/9jehvhH4nlJBLu4u0AXA1Q/Almost-Done?node-id=0%3A1). Everything can be a graphic except the title text.

### Copy in main sections
- [x] First Marketing sub-point: "Capture every missing user and event"
- [x] Product sub-heading: "Customer journeys go beyond your site and app. Finally see journeys with every service ticket, package return, and all your other interactions in one place."
- [x] First Product sub-point: "Optimize your customer funnels"

### Privacy box
- [x] Replace bullets with the following text:
> Consent and purpose limitation workflows
> Role/column-level access policies
> Auditability and observability for compliance
> Privacy-preserving data-sharing via consent management
> Privacy incident management and clearinghouse
- [x] Add check marks

### Footer
- [x] Add a period so it is: "Join our community to learn how to take analytics and marketing measurement in-house."
- [x] Decrease the weight of ^^
- [x] docs links should open in new tab

**Comment by matthewboulos** [comment]
@NejcZdovc -- FYI

**Comment by NejcZdovc** [comment]
thank you @matthewboulos. Once all of the above is addressed I will do another e2e review for Alpha

**Comment by blotoutdude** [comment]
@matthewboulos for you to review - i am suggesting an override for your text 


Text for the final section
1. Data processing in Controller Cloud Prem
2. Integrated Consent to Subject Identity (edited) 
3. Observable and Auditable Infra (edited) 
4. Governed and Secure data management (edited) 
5. Purpose limited data sharing via Server (edited) 

cc @yashghelani

**Comment by matthewboulos** [comment]
@yashghelani please use the following copy foe the privacy box (just edits of @blotoutdude comment):

1. Data processing in your cloud prem as Controller
2. Integrated consent for subject identity
3. Observable and auditable infra
4. Governed and secure data management
5. Purpose-limited data sharing

**Comment by matthewboulos** [comment]
It turns out that we have only a few additional changes left.

- [ ] Make the "Product" link in the nav point to: #explainer
- [ ] Add vertical spacing above each heading on the About page (probably 75 vs 50 top margin)

For the privacy box, let us make small logo boxes for each of the following:
- [ ] GDPR
- [ ] POPIA
- [ ] CPRA
- [ ] CCPA
- [ ] Privacy Shield
- [ ] LGPD

- [ ] Then, let us lay them out along the bottom (WIP in Figma right now)
